my_string = input("Введите произвольный текст: ")
print(my_string)
leght_of_string = len(my_string)
print("Количество символов в введённом тексте:", leght_of_string)
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ', ''))
print(my_string[0])
print(my_string[-1])
